spring.config.import=optional:file:.env[.properties]
spring.application.name=simulator
spring.data.mongodb.uri=${MONGO_URI}
server.port=${PORT:8081}
api.aviationstack.key=${AVIATIONSTACK_KEY}
api.weatherapi.key=${WEATHERAPI_KEY}
api.gemini.key=${GEMINI_KEY}
