spring.application.name=simulator
spring.data.mongodb.uri=mongodb://localhost:27017/atc_simulator
server.port=8081
api.aviationstack.key=78d6e09002bf4e2d786c2e38110414c5
api.weatherapi.key=c58d12ba75094202a2544110260803
api.gemini.key=AIzaSyBAc7KXTi6qCStahuV8MzSGtsT-cGdSNw8
