spring.application.name=simulator
spring.data.mongodb.uri=mongodb://localhost:27017/atc_simulator
server.port=8081
api.aviationstack.key=YOUR_AVIATIONSTACK_API_KEY
api.weatherapi.key=YOUR_WEATHERAPI_KEY
api.gemini.key=YOUR_GEMINI_API_KEY
